[General]
compatibility-mode = 1
ipv6 = false
prefer-ipv6 = false
bypass-system = true
skip-proxy = 10.0.0.0/8, 127.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fe80::/10, localhost, *.local, captive.apple.com
tun-excluded-routes = 127.0.0.0/8
hijack-dns = *:53
dns-server = https://doh.pub/dns-query, https://dns.alidns.com/dns-query
fallback-dns-server = 119.29.29.29, 223.5.5.5, system
always-real-ip = *.lan, *.local, *.home, *.home.arpa, *.internal, *.nip.io, *.sslip.io, localhost.ptlogin2.qq.com, localhost.sec.qq.com, localhost.work.weixin.qq.com
private-ip-answer = true
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
dns-direct-fallback-proxy = true
block-quic = all-proxy
udp-policy-not-supported-behaviour = REJECT

[Proxy Group]
节点选择 = select,PROXY,DIRECT,policy-select-name=PROXY
国内服务 = select,节点选择,DIRECT,policy-select-name=DIRECT
拦截净化 = select,节点选择,REJECT,REJECT-DROP,policy-select-name=REJECT
哔哩哔哩 = select,节点选择,DIRECT,policy-regex-filter=香港|HK|🇭🇰|Hong Kong|台湾|TW|🇹🇼|Taiwan,policy-select-name=DIRECT
AIGC = select,节点选择,DIRECT,policy-regex-filter=美国|US|🇺🇸|United States,policy-select-name=PROXY
异地组网 = select,中转,回家,DIRECT,policy-select-name=DIRECT

[Rule]
# Ban list
RULE-SET,https://cdn.jsdelivr.net/gh/Lunaclavis/Lab@release/RuleSet/Drop.conf,REJECT-DROP,no-resolve
RULE-SET,https://cdn.jsdelivr.net/gh/Lunaclavis/Lab@release/RuleSet/Reject.conf,拦截净化,no-resolve

# SNS
RULE-SET,https://cdn.jsdelivr.net/gh/Lunaclavis/Lab@release/RuleSet/SNS.conf,节点选择,no-resolve

# AIGC
RULE-SET,https://cdn.jsdelivr.net/gh/Lunaclavis/Lab@release/RuleSet/AIGC.conf,AIGC,no-resolve

# 哔哩哔哩
RULE-SET,https://cdn.jsdelivr.net/gh/Lunaclavis/Lab@release/RuleSet/Bilibili.conf,哔哩哔哩,no-resolve

# 苹果
RULE-SET,https://cdn.jsdelivr.net/gh/Lunaclavis/Lab@release/RuleSet/Apple.conf,国内服务,no-resolve

# Global
DOMAIN-SET,https://cdn.jsdelivr.net/gh/Lunaclavis/Lab@release/RuleSet/Global.conf,节点选择

# Domestic
USER-AGENT,QQ*,国内服务
USER-AGENT,WeChat*,国内服务
USER-AGENT,MicroMessenger*,国内服务
DOMAIN-SET,https://cdn.jsdelivr.net/gh/Lunaclavis/Lab@release/RuleSet/Domestic.conf,国内服务

# LAN
IP-CIDR,0.0.0.0/8,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,100.64.0.0/10,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,169.254.0.0/16,DIRECT
IP-CIDR,172.16.0.0/22,异地组网
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,192.168.12.0/24,异地组网
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,224.0.0.0/4,DIRECT
IP-CIDR,240.0.0.0/4,DIRECT
IP-CIDR,::/127,DIRECT
IP-CIDR,FC00::/7,DIRECT
IP-CIDR,FE80::/10,DIRECT
IP-CIDR,FF00::/8,DIRECT

# Final
GEOIP,CN,国内服务
FINAL,节点选择

[Host]
localhost = 127.0.0.1
*.lan = server:system
*.local = server:system
*.home = server:system
*.home.arpa = server:system
*.in-addr.arpa = server:system
*.ip6.arpa = server:system
*.internal = server:system

[URL Rewrite]
^https?://(www.)?g.cn($|/.*) https://www.google.com$2 302
^https?://(www.)?google.cn($|/.*) https://www.google.com$2 302
